### PUT request to example server
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{
  "name": "John Doe updated",
  "email": "John.doe1@example.com",
  "dateOfBirth": "1994-09-09",
  "address": "123 main street"
}

###